Git checkout  b simonigild/sc 224
Forza-Grasp/Fleet-management-Backend pull request #29
Opened 2022-11-29 13:18 UTC by ChineseThunder

2022-11-29 15:32 UTC, IfMalthereturnawesome requested changes
SpecificCarModelResponse har en constructor jeg ikke forstår, kan du rette den?

2022-11-30 08:41 UTC, Johannes-Forsting approved these changes

2022-11-30 08:42 UTC, Johannes-Forsting approved these changes

2022-11-30 13:21 UTC, Johannes-Forsting approved these changes

2022-11-30 14:03 UTC, merged